version: "3"

networks:
  gitea:
    external: false

services:
  gitea_app:
    # gitea 
    #  マイナーバージョンの変更＝DBの変更
    #  マイナーバージョン5程度がDBマイグレ可能な範囲
    image: gitea/gitea:1.15.3
    # image: gitea/gitea:1.12
    # image: gitea/gitea:1.6
    # image: gitea/gitea:1.0
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea_db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: unless-stopped
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /gogs-repositories:/repositories
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
     - "4000:3000"
     - "2221:22"
    depends_on:
      - gitea_db

  gitea_db:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    ports:
     - "5433:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
